### ISSUE TITLE
Censoring options not changing after disabling an override

### ISSUE THREAD

**Issue by jesseluvsheels** [silveredgold/beta-protection#40] opened 2023-03-04 13:14 UTC
Not only does it not drop the settings from the override, it keeps them when setting a new override.

**Comment by silveredgold** [comment] 2023-03-07 07:47
Aah interesting if it is caused by disabling an override, I'll need to look into this.

**Comment by silveredgold** [comment] 2023-04-06 06:11
Theoretically, this has been fixed in v0.2.4. Can you try it again after updating and see if it works?

**Comment by jesseluvsheels** [comment] 2023-04-07 13:16
This has been fixed so far as I can tell. Though can't test for another week.

**Closed** 2023-07-23 06:21 UTC
